networks:
  loki:

services:
  # Loki 读节点
  read:
    image: grafana/loki:latest
    command: "-config.file=/etc/loki/config.yaml -target=read"
    volumes:
      - ./config/loki-config.yaml:/etc/loki/config.yaml
    networks:
      loki:
        aliases:
          - loki
    depends_on:
      - minio

  # Loki 写节点
  write:
    image: grafana/loki:latest
    command: "-config.file=/etc/loki/config.yaml -target=write"
    volumes:
      - ./config/loki-config.yaml:/etc/loki/config.yaml
    networks:
      loki:
        aliases:
          - loki
    depends_on:
      - minio

  # Loki 后端处理
  backend:
    image: grafana/loki:latest
    command: "-config.file=/etc/loki/config.yaml -target=backend -legacy-read-mode=false"
    volumes:
      - ./config/loki-config.yaml:/etc/loki/config.yaml
    networks:
      - loki
    depends_on:
      - gateway

  # Nginx 网关
  gateway:
    image: nginx:latest
    volumes:
      - ./config/nginx-gateway.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "3100:3100"
    networks:
      - loki
    depends_on:
      - read
      - write

  # Alloy 采集器
  alloy:
    image: grafana/alloy:latest
    command: run --server.http.listen-addr=0.0.0.0:12345 --storage.path=/var/lib/alloy/data /etc/alloy/config.alloy
    volumes:
      - ./config/alloy-config.alloy:/etc/alloy/config.alloy:ro
      - /var/run/docker.sock:/var/run/docker.sock
      # 注意：挂载你的本地日志目录到容器内
      - D:/applicationfile/idea/fp_worldx/logs:/logs:ro
    ports:
      - 12345:12345
    networks:
      - loki
    depends_on:
      - gateway

  # MinIO 存储
  minio:
    image: minio/minio
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /data/loki-data && \
        mkdir -p /data/loki-ruler && \
        minio server /data --address ":9000" --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=loki
      - MINIO_ROOT_PASSWORD=supersecret
    ports:
      - "9005:9000"    # <--- 把左边的 9000 改成 9005
      - "9001:9001"    # 映射 MinIO 的控制台端口，方便你登录看文件
    volumes:
      - ./.data/minio:/data
    networks:
      - loki

  # Grafana 可视化
  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    ports:
      - "3000:3000"
    networks:
      - loki
    depends_on:
      - gateway

  # 模拟日志源
  flog:
    image: mingrammer/flog
    command: -f json -d 200ms -l
    networks:
      - loki