networks:
  loki:

services:
  # --- 指标监控层 ---
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - loki
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped

  # --- 日志存储层 (Loki) ---
  read:
    image: grafana/loki:latest
    command: "-config.file=/etc/loki/config.yaml -target=read"
    volumes:
      - ./config/loki-config.yaml:/etc/loki/config.yaml
    networks:
      loki:
        aliases:
          - loki
    depends_on:
      - minio

  write:
    image: grafana/loki:latest
    command: "-config.file=/etc/loki/config.yaml -target=write"
    volumes:
      - ./config/loki-config.yaml:/etc/loki/config.yaml
    networks:
      loki:
        aliases:
          - loki
    depends_on:
      - minio

  backend:
    image: grafana/loki:latest
    command: "-config.file=/etc/loki/config.yaml -target=backend -legacy-read-mode=false"
    volumes:
      - ./config/loki-config.yaml:/etc/loki/config.yaml
    networks:
      - loki
    depends_on:
      - gateway

  # --- 网关与存储 ---
  gateway:
    image: nginx:latest
    volumes:
      - ./config/nginx-gateway.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "3100:3100"
    networks:
      - loki
    depends_on:
      - read
      - write

  minio:
    image: minio/minio
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /data/loki-data && \
        mkdir -p /data/loki-ruler && \
        minio server /data --address ":9000" --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=loki
      - MINIO_ROOT_PASSWORD=supersecret
    ports:
      - "9005:9000"
      - "9001:9001"
    volumes:
      - ./.data/minio:/data
    networks:
      - loki

  # --- 采集层 (Alloy) ---
  alloy:
    image: grafana/alloy:latest
    command: run --server.http.listen-addr=0.0.0.0:12345 --storage.path=/var/lib/alloy/data /etc/alloy/config.alloy
    volumes:
      - ./config/alloy-config.alloy:/etc/alloy/config.alloy:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - D:/applicationfile/idea/fp_worldx/logs:/logs:ro
    ports:
      - "12345:12345"
    networks:
      - loki
    depends_on:
      - gateway

  # --- 展示层 (Grafana) ---
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - TZ=Asia/Shanghai
    networks:
      - loki
    depends_on:
      - prometheus
      - gateway
    restart: unless-stopped

  # --- 模拟日志源 ---
  flog:
    image: mingrammer/flog
    command: -f json -d 200ms -l
    networks:
      - loki